- push.sh
In this case, we will want to run check on `--all`.
> Special case the git hash of all zeros

- .github/renovate.json5
Renovate PRs should just get merged when a reviewer approves.
> chore(renovate): allow auto-merging

- action.yaml
We should still attempt to `trunk check` if any of these steps fail
> feat: allow node_modules set up to fail

- action.yaml
Reverts trunk-io/trunk-action#59
Bizarrely, this appears to be causing issues with `trunk check` - I don't understand how
> Revert "feat: allow node_modules set up to fail"

- action.yaml
Mark the check run as failed if one was passed in and we didn't apply a final status to it. This will cover cases where the CLI crashes or the service RPCs fail.
[Manual test](https://github.com/prawn-test-staging-rw/check-web/pull/2294/checks?check_run_id=12411615007):
> feat: support finalizing the check run

- action.yaml
In the return value of `github.rest.checks.get()`, `status` is the HTTP response code; `data.status` is the field that's `in_progress|completed`
> fix: check-run-id finalization logic is wrong

- action.yaml
This allows us to ship changes to the CheckService->trunk-action callpath without needing to make changes to the workflow file we put in folks' `.trunk` repo.
> feat: open client_payload in trunk-action, not check-service.yaml

- action.yaml
This will allow us to compare workflow-driven and service-driven landing states
> feat: upload landing state as an artifact

- all.sh
Teach the trunk-action to correctly download the upstream ref (`git fetch origin $ref` over `git fetch $ref`).
Also make it so that if `get-latest-raw-upload` fails, we show the failure, but preserve the current fail open behavior (and also document why it's important!)
Tested:
```
sam@sam-dell:2023-04-12T10:56:09-0700:~/trunk (main) [1]
$ INPUT_TRUNK_TOKEN=token INPUT_UPLOAD_SERIES=main2 TRUNK_PATH=tools/trunk INPUT_CHECK_ALL_MODE=hold-the-line INPUT_DEBUG=false ~/action/all.sh
++ 2023-04-12T10:56:17-0700 ++ INPUT_TRUNK_TOKEN=token
++ 2023-04-12T10:56:17-0700 ++ INPUT_UPLOAD_SERIES=main2
++ 2023-04-12T10:56:17-0700 ++ TRUNK_PATH=tools/trunk
++ 2023-04-12T10:56:17-0700 ++ INPUT_CHECK_ALL_MODE=hold-the-line
++ 2023-04-12T10:56:17-0700 ++ INPUT_DEBUG=false
++ 2023-04-12T10:56:17-0700 ++ …
```
> feat: fix upstream download

- action.yaml
This caused us to hit our artifact storage limit. Customers will also probably hit this.
Ignore upload errors, also only upload for PR runs.
> fix: ignore landing state upload failures

- action.yaml
This was previously in `check-service.yaml`, but on further reflection it should really just happen inside `trunk-action`. See https://github.com/trunk-io/.trunk/commit/057731b848b2fc678571dffc3c01da53b197533f; changes in CheckService are incoming.
> feat: push checkout logic into trunk-action

- all.sh
- pull_request.sh
- push.sh
- trunk_merge.sh
--output-file is not supported in old versions of trunk.
We'll want to set this ourselves for our own dogfooding via `INPUT_ARGUMENTS=--output-file=.trunk/landing-state.json` in `.trunk/setup-ci/`.
> fix: do not blindly write out landing-state.json

- .github/workflows/repo_tests.yaml
- repo_tests/check_for_task_failures.py
- setup-env/action.yaml
The repo tests now return an error instead of success if landing-state.json does not exist. Additionally, the job will show as failed if any individual job fails (and it still runs all tests, rather than quitting on the first fail).
I also bumped all the refs for the repos to latest main.
However, several repos fail the test, all for different reasons, and I'm not quite sure how to handle that:
- vuejs/core fails because pnpm version is too new
- shopify/draggable fails because webpack doesn't work with newest npm: https://github.com/webpack/webpack/issues/14532
- sheldonhull/sheldonhull.hugo fails because yarn install would update the yarn lockfile
- pallets/flask fails because of a linter failure in an invalid html file
I'm PRing this now to get eyes on it, despite likely needing to fix …
> Fix repo tests to error if trunk-check doesn't run

- action.yaml
- setup-env/action.yaml
Following the same logic as in #93, this PR adds caching first by repo and branch, then just by repo. This can be seen [here](https://github.com/trunk-io/trunk-action/actions/runs/4824047000/jobs/8593330977).
This PR depends on #93 and [trunk-io/trunk#8408](https://github.com/trunk-io/trunk/pull/8408).
> Feat: cache node modules

- .github/workflows/repo_tests.yaml
- setup-env/action.yaml
We have never passed a node version into the setup-node action, making that action a no-op. This worked previously because the github `ubuntu-latest` runners have node installed by default. However, after switching over to our self-hosted runners that do not have node installed, the action started failing.
This PR adds logic to detect files that have the node version, and pass them into the setup_node action to be parsed. It also adds shopify/draggable back to the repo_tests, as it was failing because the node version was too new.
> fix: actually install node during setup

- setup-env/action.yaml
The $GITHUB_OUTPUT syntax we used to use requires upgrading our self-hosted runners. This reworks that logic to use environment variables instead.
See successful tests [here](https://github.com/trunk-io/trunk-action/actions/runs/4886568250/jobs/8722079211) (and hopefully on this PR, as well).
> fix: switch from GitHub output to GitHub env

- .github/workflows/repo_tests.yaml
- action.yaml
- setup-env/action.yaml
Because all of the caching is done in the .trunk repo, the caches for different repos in the same org stomp on each other. This introduces different keys for different repos. This can be seen in the [repo_tests running on this PR](https://github.com/trunk-io/trunk-action/actions/runs/4887481583/jobs/8724116197?pr=93). 
Additionally, this PR adds caching for the `node_modules` folder, following the same caching logic.
This has an associated PR in trunk-io/trunk, [#8408](https://github.com/trunk-io/trunk/pull/8408).
> fix: cache linters/formatters correctly

- action.yaml
Going via CheckService allows us to no longer have to worry about the GH token expiring too soon; in exchange, we have to accept that there are CLI->CheckService gaps we may not have coverage for.
This will, however, ensure coverage of the case where something in normal "trunk check" goes wrong, which is the primary case that we're concerned about.
> feat: finalize via CheckService instead of the GH API

- .github/workflows/repo_tests.yaml
- action.yaml
- setup-env/action.yaml
Teaching auto-init to also install Node deps was, besides being a potentially surprising change, also broke users who configure allowlists for the set of actions that may be run in their repositories. We fix this as follows:
* move the automatic `trunk init` from the setup-env sub-action to the top-level action
* run setup-env if `inputs.setup-env` is `true` or if the CheckService call sets it to true
* i.e. skip setup-env by default, but run it in all other scenarios
* if `.trunk/setup-ci/` exists, run that instead (regardless of the value of `inputs.setup-env`)
We have to pull the `trunk init` up a level because the actions allowlist setting enforcement is actually split between compile time and runtime:
* when the actions runner runs a composite action, it downloads the `uses` for …
> fix: make node setup opt-in

- upgrade/action.yaml
Follow-up to #105 but for trunk-action/upgrade.
Testing:
- Running with setup-ci: true, triggering an allowlist violation: https://github.com/prawn-test-staging-rw/check-web/pull/19429
- Running without setup-ci, triggering a successful run: https://github.com/prawn-test-staging-rw/check-web/pull/19430
Note that in both cases, I had to add `peter-evans/create-pull-request@*` to the allowlist in order for the upgrade to work.
> fix: Make setup deps opt-in for upgrade

- action.yaml
This is step 1 of 6 to clean up the trunk check workflow inputs:
1. change trunk-action to accept either clientPayload.token or clientPayload.trunkToken ([trunk-action#116](https://github.com/trunk-io/trunk-action/pull/116))
2. change .trunk-internal extra inputs to not be required and use github event path ([.trunk-internal#6](https://github.com/trunk-io/.trunk-internal/pull/6))
3. change monorepo to not have extra inputs ([trunk#9070](https://github.com/trunk-io/trunk/pull/9070))
4. staging deploy
5. change .trunk-internal to remove extra inputs ([.trunk-internal#7](https://github.com/trunk-io/.trunk-internal/pull/7))
6. change trunk action to not use json or token inputs ([trunk-action#117](https://github.com/trunk-io/trunk-action/pull/117))
> fix: accept clientPayload.token or clientPayload.trunkToken

- upgrade/action.yaml
Specify which paths should be added to the generated PR. Default `.trunk`, but needs to be `plugin.yaml` for https://github.com/trunk-io/configs/pull/3.
[Demonstrated successful run](https://github.com/trunk-io/configs/actions/runs/5204635588/jobs/9389113298?pr=3)
> Specify specific paths for upgrade

- action.yaml
This is step 6 of 6 to clean up the trunk check workflow inputs:
1. change trunk-action to accept either clientPayload.token or clientPayload.trunkToken ([trunk-action#116](https://github.com/trunk-io/trunk-action/pull/116))
2. change .trunk-internal extra inputs to not be required and use github event path ([.trunk-internal#6](https://github.com/trunk-io/.trunk-internal/pull/6))
3. change monorepo to not have extra inputs ([trunk#9070](https://github.com/trunk-io/trunk/pull/9070))
4. staging deploy
5. change .trunk-internal to remove extra inputs ([.trunk-internal#7](https://github.com/trunk-io/.trunk-internal/pull/7))
6. change trunk action to not use json or token inputs ([trunk-action#117](https://github.com/trunk-io/trunk-action/pull/117))
> fix: remove json and token inputs

- action.yaml
Teach trunk-action to always call the CheckService instance that dispatched it.
Also set TRUNK_TOKEN; we should stop using INPUT_TRUNK_TOKEN and explicitly wiring it through everywhere
> feat: wire through TRUNK_API_ADDRESS

- upgrade/action.yaml
Add support for adding **optional** prefixes in PR title.
Can be useful in a repo that utilizes conventional commits.
```yml
name: trunk
on:
workflow_dispatch:
permissions: read-all
jobs:
upgrade:
name: upgrade trunk
runs-on: ubuntu-latest
permissions:
contents: write
pull-requests: write
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Trunk Upgrade
uses: trunk-io/trunk-action/upgrade@main
with:
prefix: "deps:"
```
> feat: support for PR title prefix in upgrade action

- fetch.sh
- locate_trunk.sh
As seen in [this failing upload](https://github.com/trunk-io/trunk/actions/runs/5257114644/jobs/9499436500), if the launcher can't find the specified version of trunk in the cache, it downloads it and prints logs, which can output junk into variables that we use for logic.
This bandaid fixes the issue by running trunk immediately, downloading it and printing the logs before it can corrupt anything.
> fix: download trunk version before depending on its output

- action.yaml
CheckService-driven invocations should always set this; it causes no issues with checking out repos without LFS artifacts.
> fix: always checkout with lfs=true

- .github/workflows/repo_tests.yaml
- action.yaml
- fetch.sh
- pull_request.sh
- repo_tests/check_for_task_failures.py
- trunk_merge.sh
Fixes [TRUNK-7598](https://linear.app/trunk/issue/TRUNK-7598/stop-passing-token-explicitly-in-trunk-action) - we can infer the trunk token from the TRUNK_TOKEN environment variable, so we don't need to pass it in with `--token` in most calls to the cli. The exception is in check-mode all, which is the path taken by cli version 1.0.0.
This PR removes most calls to `--token`, and adds a compatibility test to repo_tests for 1.0.0.
> fix: remove unnecessary calls to --token

- input-setup/mask.js
Tested on a workflow run [here](https://github.com/trunk-io/trunk/actions/runs/5316026661/jobs/9625099192) on [maverick/test-actions-token-typo-fix](https://github.com/trunk-io/trunk/tree/maverick/test-actions-token-typo-fix) in the monorepo (run just on pylint so it doesn't take forever)
We haven't been correctly propagating the trunk token, causing our upload workflows to fail, just running trunk check rather than uploading the issues. As a result, it "fixes" [TRUNK-7582](https://linear.app/trunk/issue/TRUNK-7582/check-upload-should-not-print-detected-issues) - the reason we were printing the issues is because we weren't running the upload.
> fix: correctly add token from input

- action.yaml
* If `trunk check` fails, the job should fail; right now it always succeeds because the finalize step has `always()` and `continue-on-error: true`
* c.f. https://github.com/trunk-io/.trunk-internal/actions/runs/5405370271/jobs/9820824695
* Landing state upload should only happen if set to `"true"`
* c.f. https://github.com/sxlijin/repro/actions/runs/5405792565/jobs/9821834283
* We no longer need to do client-side finalization, because we do it all from CheckService
> fix: job success should reflect trunk check success

- .github/workflows/docker_repo_tests.yaml
- .github/workflows/repo_tests.yaml
TRUNK-7656 has been fixed, so we can re-enable bandit.
> fix: re-enable bandit on flask repo test

- .github/workflows/action_tests.yaml
- .github/workflows/pr.yaml
- .gitignore
- action_tests/assert.js
- action_tests/stub.js
- package-lock.json
- package.json
- trunk_merge.sh
Passing `"${annotation_argument}"` results in another empty string being passed into `trunk check` during `trunk_merge.sh`, which the CLI interprets as "attempt to lint the file with name `""`".
Passing `${annotation_argument}` results in Bash not passing anything to `trunk check`, which results in the correct behavior.
Also set up tests for `trunk_merge.sh` - it's not the greatest, but it's better than nothing.
> fix: make trunk_merge work again when invoked normally

- .github/workflows/action_tests.yaml
- .github/workflows/pr.yaml
- action_tests/assert.js
- action_tests/setup.sh
- action_tests/stub.js
- all.sh
* the CLI now does not print "UNSPECIFED" in messages when starting a new series; it only prints "Starting new series" (see trunk-io/trunk#9721)
* stop explicitly passing `--token` in the `check_all_mode: hold-the-line` path - the CLI now respects `TRUNK_TOKEN` and #142 removed the explicit passing in most paths, except for the ones in `all.sh`
> fix: use correct regex for new series in all.sh

- .github/workflows/action_tests.yaml
- action_tests/assert.js
- action_tests/stub.js
- all.sh
Currently, if a user kicks off a workflow in a repo that already has a trunk.yaml that specifies a CLI version < 1.12.3, it will fail when tries to use `--upload-id`. This PR adds a check for this, and prints an error message if the CLI is too old.
> fix: print error message if CLI is too old to use upload id

- .github/workflows/action_tests.yaml
- action_tests/assert.js
- pull_request.sh
- trunk_merge.sh
Adds a check similar to #171, but for `--trunk-annotate`.
CLI version 1.7.0 is the earliest prod CLI version after [trunk#7540](https://github.com/trunk-io/trunk/pull/7540).
> add test for cli version for INPUT_CHECK_RUN_ID in action

- all.sh
- pull_request.sh
- trunk_merge.sh
`sort --version-sort` doesn't exist on some systems, so adding in a check for its return value before depending on the result.
> fix: don't fail the workflow if sort --version-sort doesn't exist

- .github/workflows/repo_tests.yaml
- package.json
- setup-env/action.yaml
Continues if the setup-node action fails to install, and then installs latest node if there is no node version installed. Judging by [this website](https://node.green/) showing note compatibilities, node is almost entirely backwards compatible, which is why I went with the latest version rather than e.g. node 20.
Additionally, adds a node version to the package.json so that this PR can merge - the v1 action version still chokes when not finding the node version.
This is tested by adding the trunk-action repo to the [repo tests](https://github.com/trunk-io/trunk-action/actions/runs/6156480974/job/16705376207?pr=186), which does not have a node version in main. However, the runners have node installed, so the action doesn't attempt to install a default version - I'm not sure if there's a …
> fix: install latest node if setup-node fails

- .github/workflows/repo_tests.yaml
But we only care about the clang-tidy integration, not the markdownlint integration.
> chore: jbeder/yaml-cpp repo_test has been failing for a while

- upgrade/action.yaml
- upgrade/upgrade.sh
Adds 'lowercase-title' option to the 'trunk-action/upgrade' action. Specifying the option converts the PR / commit title "Upgrade trunk" to lowercase, i.e. "upgrade trunk"
Example usage:
- uses: trunk-io/trunk-action/upgrade@v1 with: prefix: "chore(deps): " lowercase-title: true
This change makes it possible to use the trunk upgrade action in a way that conforms to the commitlint '@commitlint/config-conventional' configuration which specifies that commit message subject must not be sentence-case, start-case, pascal-case, upper-case. With the default commit message title "Upgrade trunk" and `prefix: "chore(deps): "` the following error is emitted by commitlint using `config-conventional`:
⧗   input: chore(deps): Upgrade trunk to 1.19.0
✖   subject must not be sentence-case, start-case, …
> feat: add 'lowercase-title' option to upgrade action

- upgrade/action.yaml
Fixes the path to `locate_trunk.sh` and bumps the `create-pull-request` to v6.
Successful [run](https://github.com/trunk-io/trunk-action/actions/runs/8145406935/job/22261584720) and [PR](https://github.com/trunk-io/trunk-action/pull/230)
> Fix upgrade action setup

- .github/workflows/pr.yaml
- .github/workflows/repo_tests.yaml
- action.yaml
- setup-env/action.yaml
Currently, most of our check-on-prs/check nightly failures occur while installing node packages, for a variety of reasons. Right now, this causes the check to fail, and we report that "something went wrong". Instead, we may want to disable linters that depend on node-modules (specifically, stylelint and eslint) and lint the remaining files to report our best-effort results.
Pros:
- We would report some issues, and some issues is better than no issues
- We wouldn't be erroring with a message that seems like an internal error (because for all we know right now, it could be)
Cons:
- A user could introduce a lint issue in the same PR as a breaking change to package.json and we would pass that PR
- I am pretty sure that we don't have a great way of surfacing to the user that we're disabling …
> feat: continue on node package install failure

- .github/workflows/weekly.yaml
- .trunk/trunk.yaml
- upgrade/action.yaml
Per a user request, adds the following:
- Input for assignees
- Input to override the default created branch name
- Output the PR number and other PR info for consumption from other actions
Verified [run](https://github.com/trunk-io/trunk-action/actions/runs/9038985803/job/24841100064)
> Add inputs/outputs to upgrade action

- setup-env/action.yaml
Currently, we only install the latest pnpm version, which fails if the user has specified a pnpm version under `packageManager` in their package.json. This PR changes that to attempt to parse the version out of the package.json before defaulting to latest.
The `pnpm/action-setup` action does have logic for parsing the version out of the package.json, but we cannot provide both an version and a version in the package.json, or it will fail ([source link](https://github.com/pnpm/action-setup/blob/master/src/install-pnpm/run.ts#L64)).
Tested manually, both with and without the `packageManager` field.
> fix: attempt to install specified pnpm version

- .github/workflows/action_tests.yaml
- action.yaml
There may be times where the trunk action is unresponsive and is hung in CI.
To understand whether this is a linter or trunk cli issue, we'll need logs to confirm.
This PR adds the following optional inputs `timeout-seconds` and `cat-trunk-debug-logs`
which will wrap the trunk check action with the unix `timeout` command should the user supply an argument for `timeout-seconds`
Should the user specify `cat-trunk-debug-logs: true`, the trunk action will also cat out cli & daemon logs from `.trunk/logs/`
Unfortunately, `timeout-minutes` doesn't work in `composite-actions` see https://github.com/actions/runner/issues/1979
and https://github.com/orgs/community/discussions/50481
**Test Plan**:
<details>
<summary>End to End test to ensure timeout + logs work</summary>
</details>
<details> …
> [feat] add timeout and ability to cat debug logs

- .github/workflows/docker_repo_tests.yaml
- action.yaml
Adds the option to disable LFS checkout either from services or as an input.
Also, updates the registry for the docker image because docker tests were failing with permission issues
Tested manually - tests here are failing for unrelated reasons.
> feat: make LFS checkout optional

- action.yaml
This will silence a warning about using Node 16, in favor of using Node 20.
> Update actions/cache@v3 to actions/cache@v4

- .github/workflows/docker_repo_tests.yaml
- .github/workflows/repo_tests.yaml
- .github/workflows/scorecard.yml
- action.yaml
actions/upload-artifact@v3 will be unusable in 2 months ([announcement link](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/))
> chore: bump upload-artifact action dependency

- upgrade/action.yaml
This adds the input parameter `labels`.
I think this is a needed parameter because some repos have different label schemas than "trunk".
Example: I would like to add "area: dependencies" as label instead of "trunk".
> feat(upgrade): add labels input parameter

- all.sh
This affects all HTL mode as well, so message unconditionally
Warning shown [here](https://github.com/trunk-io/trunk-action/actions/runs/14869911069/job/41755755389)
> (Chore): Add deprecation notice for check uploads

- action.yaml
Checks the check mode to provide the deprecation notice. Additionally, only tries to post comment if the github token exists. Tested with and without a .trunk/setup-ci
> fix: use correct check for check on PRs

- action.yaml
Changes the comment posting so it only happens on checking PRs, not on checking merge. Additionally, adds a continue on error, so that if there are future errors, they aren't blocking.
> fix: only post comment when checking PRs

- upgrade/action.yaml
I want to use automated trunk updates in a repository where all commits need to be signed. 
So I thought about adding it to the github action because the `create-pull-request` action that is used here has support for signed commits using GitHub API starting with v7.
So I upgraded `create-pull-request` to v7 and added a new input value to enable signing.
I am using my forked action currently and its working fine but I would like to contribute this to you :)
> feat(upgrade): update create-pull-request to v7 and add sign-commits input parameter
